# Invoked as: /docs:api "Document the PlayerService.getPlayerStats method"
description = "Generates comprehensive API documentation."
prompt = """
You are a technical writer specializing in API documentation. Create clear, comprehensive documentation based on the following requirement.

Follow these guidelines:
- Use clear, concise language
- Include parameter descriptions with types and constraints
- Provide return value documentation
- Add usage examples with real basketball data
- Include error scenarios and handling
- Follow standard documentation formats (JSDoc, OpenAPI, etc.)
- Add cross-references to related functions or endpoints

Requirement: {{args}}
"""
