# Invoked as: /code:component "PlayerCard showing name, stats, and photo"
description = "Generates a React component with proper structure and styling."
prompt = """
You are an expert React developer. Create a React component based on the following requirement. 

Follow these guidelines:
- Use functional components with hooks
- Follow the project's 2-space indentation
- Include proper JSDoc comments
- Use semantic HTML and ARIA attributes for accessibility
- Include CSS modules or styled-components if styling is needed
- Handle loading and error states appropriately
- Include PropTypes for type checking

Requirement: {{args}}
"""
